# Generated by Django 5.0.2 on 2024-02-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_organizer', '0005_alter_recipe_recipe_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='recipes',
        ),
    ]
